	<ul class="menutop level1 " >
						<li class="item1 root" >
					<a class="orphan item bullet" href="http://www.sky.gr/"  >
				<span>
			    				Αρχική				   
				</span>
			</a>
			
			
	</li>	
							<li class="item54 parent root" >
					<a class="daddy item bullet" href="/index.php/news"  >
				<span>
			    				Ενημέρωση				   
				</span>
			</a>
			
					<div class="fusion-submenu-wrapper level2">
				<div class="drop-top"></div>
				<ul class="level2">
								
							<li class="item56" >
					<a class="orphan item bullet" href="/index.php/news/generic"  >
				<span>
			    				Γενικά				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item57" >
					<a class="orphan item bullet" href="/index.php/news/comps"  >
				<span>
			    				Αγώνες				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item58" >
					<a class="orphan item bullet" href="/index.php/news/events"  >
				<span>
			    				Εκδηλώσεις				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item59" >
					<a class="orphan item bullet" href="/index.php/news/press-releases"  >
				<span>
			    				Δελτία Τύπου				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item60" >
					<a class="orphan item bullet" href="/index.php/news/about-skygr"  >
				<span>
			    				Σχετικά με το Sky.gr				   
				</span>
			</a>
			
			
	</li>	
										</ul>
			</div>
			
	</li>	
							<li class="item163 parent root" >
					<span class="daddy item bullet nolink">
			    <span>
			        			    Ειδήσεις			    			    </span>
			</span>
			
					<div class="fusion-submenu-wrapper level2">
				<div class="drop-top"></div>
				<ul class="level2">
								
							<li class="item165" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/fai-civl"  >
				<span>
			    				F.A.I. CIVL				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item164" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/paragliding-world-cup"  >
				<span>
			    				Paragliding World Cup				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item166" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/cross-country"  >
				<span>
			    				Cross Country				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item167" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/paragliding-forum"  >
				<span>
			    				Paragliding Forum				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item168" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/dhv-safety"  >
				<span>
			    				DHV Safety				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item170 parent" >
					<a class="daddy item bullet" href="/index.php/2010-12-26-17-18-42/blogs"  >
				<span>
			    				Blogs				   
				</span>
			</a>
			
					<div class="fusion-submenu-wrapper level3">
				<div class="drop-top"></div>
				<ul class="level3">
								
							<li class="item171" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/blogs/2010-12-27-19-47-43"  >
				<span>
			    				Α.Σ. Πέλλα				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item173" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/blogs/2010-12-27-19-48-59"  >
				<span>
			    				Α.Ο. Κιθαιρώνα				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item174" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/blogs/2010-12-27-19-49-52"  >
				<span>
			    				ΑΕΦΙΠ				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item175" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/blogs/fokidasky"  >
				<span>
			    				fokidasky				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item176" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/blogs/sotlion"  >
				<span>
			    				sotlion				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item177" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/blogs/no-limits-blog"  >
				<span>
			    				no-limits-blog				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item178" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/blogs/gatsinik"  >
				<span>
			    				gatsinik				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item179" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/blogs/paragliding-giotar"  >
				<span>
			    				paragliding-giotar				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item180" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/blogs/drflight"  >
				<span>
			    				drflight				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item181" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-17-18-42/blogs/kostasfreedom"  >
				<span>
			    				kostasfreedom				   
				</span>
			</a>
			
			
	</li>	
										</ul>
			</div>
			
	</li>	
										</ul>
			</div>
			
	</li>	
							<li class="item55 parent root" >
					<a class="daddy item bullet" href="/index.php/articles"  >
				<span>
			    				Θέματα				   
				</span>
			</a>
			
					<div class="fusion-submenu-wrapper level2">
				<div class="drop-top"></div>
				<ul class="level2">
								
							<li class="item61" >
					<a class="orphan item bullet" href="/index.php/articles/generic"  >
				<span>
			    				Γενικά Θέματα				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item62 parent" >
					<a class="daddy item bullet" href="/index.php/articles/admin-and-comps"  >
				<span>
			    				Διοικητικά - Αγωνιστικά				   
				</span>
			</a>
			
					<div class="fusion-submenu-wrapper level3">
				<div class="drop-top"></div>
				<ul class="level3">
								
							<li class="item84" >
					<a class="orphan item bullet" href="/index.php/articles/admin-and-comps/wprs-countries"  >
				<span>
			    				Κατάταξη FAI - Χώρες				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item85" >
					<a class="orphan item bullet" href="/index.php/articles/admin-and-comps/wprs-greece"  >
				<span>
			    				Κατάταξη FAI - Ελλάδα				   
				</span>
			</a>
			
			
	</li>	
										</ul>
			</div>
			
	</li>	
									
							<li class="item63" >
					<a class="orphan item bullet" href="/index.php/articles/user-articles"  >
				<span>
			    				Άρθρα Μελών				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item64" >
					<a class="orphan item bullet" href="/index.php/articles/intro-to-paragliding"  >
				<span>
			    				Αλεξίπτωτο Πλαγιάς				   
				</span>
			</a>
			
			
	</li>	
										</ul>
			</div>
			
	</li>	
							<li class="item75 parent root" >
					<a class="daddy item bullet" href="/index.php/training"  >
				<span>
			    				Εκπαίδευση				   
				</span>
			</a>
			
					<div class="fusion-submenu-wrapper level2">
				<div class="drop-top"></div>
				<ul class="level2">
								
							<li class="item76" >
					<a class="orphan item bullet" href="/index.php/training/schools"  >
				<span>
			    				Σχολές				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item77" >
					<a class="orphan item bullet" href="/index.php/training/rules"  >
				<span>
			    				Κανονισμοί				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item78" >
					<a class="orphan item bullet" href="/index.php/training/exams"  >
				<span>
			    				Εξετάσεις				   
				</span>
			</a>
			
			
	</li>	
										</ul>
			</div>
			
	</li>	
							<li class="item65 parent active root" >
					<a class="daddy item bullet" href="/index.php/forum"  >
				<span>
			    				Forum				   
				</span>
			</a>
			
					<div class="fusion-submenu-wrapper level2">
				<div class="drop-top"></div>
				<ul class="level2">
								
							<li class="item72" >
					<a class="orphan item bullet" href="http://www.sky.gr/forum/index.php?search_id=active_topics&amp;rb_v=search"  >
				<span>
			    				Ενεργά Θέματα				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item73" >
					<a class="orphan item bullet" href="http://www.sky.gr/forum/index.php?search_id=newposts&amp;rb_v=search"  >
				<span>
			    				Νέα Θέματα				   
				</span>
			</a>
			
			
	</li>	
										</ul>
			</div>
			
	</li>	
							<li class="item67 parent root" >
					<a class="daddy item bullet" href="http://www.sky.gr/leonardo/tracks/GR/alltimes/brand:all,cat:1,class:all,xctype:all,club:all,pilot:all,takeoff:all&amp;sortOrder=dateAdded"  >
				<span>
			    				Leonardo				   
				</span>
			</a>
			
					<div class="fusion-submenu-wrapper level2">
				<div class="drop-top"></div>
				<ul class="level2">
								
							<li class="item69" >
					<a class="orphan item bullet" href="http://www.sky.gr/leonardo/tracks/GR/alltimes/brand:all,cat:0,class:all,xctype:all,club:all,pilot:all,takeoff:all&amp;sortOrder=dateAdded"  >
				<span>
			    				Όλες οι πτήσεις				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item68" >
					<a class="orphan item bullet" href="http://www.sky.gr/leonardo/tracks/GR/alltimes/brand:all,cat:1,class:all,xctype:all,club:all,pilot:all,takeoff:all&amp;sortOrder=dateAdded"  >
				<span>
			    				Τελευταίες υποβολές				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item70" >
					<a class="orphan item bullet" href="http://www.sky.gr/leonardo/page/add_flight"  >
				<span>
			    				Υποβολή πτήσης				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item71" >
					<a class="orphan item bullet" href="http://www.sky.gr/leonardo/league/GR/2010/brand:all,cat:1,class:all,xctype:all,club:all"  >
				<span>
			    				Greek XC League				   
				</span>
			</a>
			
			
	</li>	
										</ul>
			</div>
			
	</li>	
							<li class="item79 parent root" >
					<a class="daddy item bullet" href=""  >
				<span>
			    				Πτήσεις				   
				</span>
			</a>
			
					<div class="fusion-submenu-wrapper level2">
				<div class="drop-top"></div>
				<ul class="level2">
								
							<li class="item80" >
					<a class="orphan item bullet" href="http://www.sky.gr/leonardo/page/sites"  >
				<span>
			    				Οδηγός Απογειώσεων				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item81" >
					<a class="orphan item bullet" href="http://www.sky.gr/leonardo/takeoffs/GR/2008/brand:all,cat:0,club:all,pilot:0_0"  >
				<span>
			    				Λίστα Απογειώσεων				   
				</span>
			</a>
			
			
	</li>	
										</ul>
			</div>
			
	</li>	
							<li class="item162 parent root" >
					<span class="daddy item bullet nolink">
			    <span>
			        			    Χρήσιμα			    			    </span>
			</span>
			
					<div class="fusion-submenu-wrapper level2">
				<div class="drop-top"></div>
				<ul class="level2">
								
							<li class="item66" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-16-16-13/weather"  >
				<span>
			    				Καιρός				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item82" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-16-16-13/calendar"  >
				<span>
			    				Ημερολόγιο				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item161" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-16-16-13/2010-12-20-09-46-46"  >
				<span>
			    				Φωτογραφίες				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item169" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-16-16-13/web-cams"  >
				<span>
			    				Web Cams				   
				</span>
			</a>
			
			
	</li>	
									
							<li class="item182" >
					<a class="orphan item bullet" href="/index.php/2010-12-26-16-16-13/2010-12-28-14-47-39"  >
				<span>
			    				Υπολογιστής				   
				</span>
			</a>
			
			
	</li>	
										</ul>
			</div>
			
	</li>	
				</ul>
