<?
/************************************************************************/
/* Leonardo: Gliding XC Server					                        */
/* ============================================                         */
/*                                                                      */
/* Copyright (c) 2004-5 by Andreadakis Manolis                          */
/* http://leonardo.thenet.gr                                            */
/*                                                                      */
/* This program is free software. You can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation; either version 2 of the License.       */
/************************************************************************/

function getTZforCountry($countryCode) {
	global $Countries2timeZones;
	return $Countries2timeZones[$countryCode];
}



$Countries2timeZones=array(
// AFRICA 
'AO'=>'Africa/Luanda',
'BF'=>'Africa/Ouagadougou',
'BI'=>'Africa/Bujumbura',
'BJ'=>'Africa/Porto-Novo',
'BW'=>'Africa/Gaborone',
'CF'=>'Africa/Bangui',
'CG'=>'Africa/Brazzaville',
'CI'=>'Africa/Abidjan',
'CM'=>'Africa/Douala',
'DJ'=>'Africa/Djibouti',
'DZ'=>'Africa/Algiers',
'EG'=>'Africa/Cairo',
'EH'=>'Africa/El_Aaiun',
'ER'=>'Africa/Asmera',
'ES'=>'Africa/Ceuta',
'ET'=>'Africa/Addis_Ababa',
'GA'=>'Africa/Libreville',
'GH'=>'Africa/Accra',
'GM'=>'Africa/Banjul',
'GN'=>'Africa/Conakry',
'GQ'=>'Africa/Malabo',
'GW'=>'Africa/Bissau',
'KE'=>'Africa/Nairobi',
'LR'=>'Africa/Monrovia',
'LS'=>'Africa/Maseru',
'LY'=>'Africa/Tripoli',
'MA'=>'Africa/Casablanca',
'ML'=>'Africa/Bamako',
'MR'=>'Africa/Nouakchott',
'MW'=>'Africa/Blantyre',
'MZ'=>'Africa/Maputo',
'NA'=>'Africa/Windhoek',
'NE'=>'Africa/Niamey',
'NG'=>'Africa/Lagos',
'RW'=>'Africa/Kigali',
'SD'=>'Africa/Khartoum',
'SL'=>'Africa/Freetown',
'SN'=>'Africa/Dakar',
'SO'=>'Africa/Mogadishu',
'ST'=>'Africa/Sao_Tome',
'SZ'=>'Africa/Mbabane',
'TD'=>'Africa/Ndjamena',
'TG'=>'Africa/Lome',
'TN'=>'Africa/Tunis',
'TZ'=>'Africa/Dar_es_Salaam',
'UG'=>'Africa/Kampala',
'ZA'=>'Africa/Johannesburg',
'ZM'=>'Africa/Lusaka',
'ZW'=>'Africa/Harare',

// AMERICA
'AG'=>'America/Antigua',
'AI'=>'America/Anguilla',
'AN'=>'America/Curacao',
'AW'=>'America/Aruba',
'BB'=>'America/Barbados',
'BO'=>'America/La_Paz',
'BS'=>'America/Nassau',
'BZ'=>'America/Belize',
'CL'=>'America/Santiago',
'CO'=>'America/Bogota',
'CR'=>'America/Costa_Rica',
'CU'=>'America/Havana',
'DM'=>'America/Dominica',
'DO'=>'America/Santo_Domingo',
'EC'=>'America/Guayaquil',
'GD'=>'America/Grenada',
'GF'=>'America/Cayenne',
'GP'=>'America/Guadeloupe',
'GT'=>'America/Guatemala',
'GY'=>'America/Guyana',
'HN'=>'America/Tegucigalpa',
'HT'=>'America/Port-au-Prince',
'JM'=>'America/Jamaica',
'KN'=>'America/St_Kitts',
'KY'=>'America/Cayman',
'LC'=>'America/St_Lucia',
'MQ'=>'America/Martinique',
'MS'=>'America/Montserrat',
'NI'=>'America/Managua',
'PA'=>'America/Panama',
'PE'=>'America/Lima',
'PM'=>'America/Miquelon',
'PR'=>'America/Puerto_Rico',
'PY'=>'America/Asuncion',
'SR'=>'America/Paramaribo',
'SV'=>'America/El_Salvador',
'TC'=>'America/Grand_Turk',
'TT'=>'America/Port_of_Spain',
'UY'=>'America/Montevideo',
'VC'=>'America/St_Vincent',
'VE'=>'America/Caracas',
'VG'=>'America/Tortola',
'VI'=>'America/St_Thomas',

// EUROPE
'AD'=>'Europe/Andorra',
'AL'=>'Europe/Tirane',
'AT'=>'Europe/Vienna',
'AX'=>'Europe/Mariehamn',
'BA'=>'Europe/Sarajevo',
'BE'=>'Europe/Brussels',
'BG'=>'Europe/Sofia',
'BY'=>'Europe/Minsk',
'CH'=>'Europe/Zurich',
'CS'=>'Europe/Belgrade',
'CZ'=>'Europe/Prague',
'DE'=>'Europe/Berlin',
'DK'=>'Europe/Copenhagen',
'EE'=>'Europe/Tallinn',
'ES'=>'Europe/Madrid',
'FI'=>'Europe/Helsinki',
'FR'=>'Europe/Paris',
'GB'=>'Europe/London',
'GI'=>'Europe/Gibraltar',
'GR'=>'Europe/Athens',
'HR'=>'Europe/Zagreb',
'HU'=>'Europe/Budapest',
'IE'=>'Europe/Dublin',
'IT'=>'Europe/Rome',
'LI'=>'Europe/Vaduz',
'LT'=>'Europe/Vilnius',
'LU'=>'Europe/Luxembourg',
'LV'=>'Europe/Riga',
'MC'=>'Europe/Monaco',
'MD'=>'Europe/Chisinau',
'MK'=>'Europe/Skopje',
'MT'=>'Europe/Malta',
'NL'=>'Europe/Amsterdam',
'NO'=>'Europe/Oslo',
'PL'=>'Europe/Warsaw',
'PT'=>'Europe/Lisbon',
'RO'=>'Europe/Bucharest',
'SE'=>'Europe/Stockholm',
'SI'=>'Europe/Ljubljana',
'SK'=>'Europe/Bratislava',
'SM'=>'Europe/San_Marino',
'TR'=>'Europe/Istanbul',
'VA'=>'Europe/Vatican',


);

?>