CREATE TABLE leonardo_flights_new (
  ID bigint(20) unsigned NOT NULL auto_increment,
  serverID smallint(5) unsigned NOT NULL default '0',
  originalURL varchar(255) NOT NULL default '',
  originalKML varchar(255) NOT NULL,
  original_ID mediumint(8) unsigned NOT NULL default '0',
  cat smallint(5) unsigned NOT NULL default '1',
  subcat smallint(5) unsigned NOT NULL default '1',
  category smallint(5) unsigned NOT NULL default '2',
  active smallint(6) NOT NULL default '0',
  dateAdded datetime NOT NULL default '0000-00-00 00:00:00',
  timesViewed mediumint(9) NOT NULL default '0',
  userID mediumint(8) unsigned NOT NULL default '0',
  originalUserID mediumint(8) unsigned NOT NULL default '0',
  userServerID mediumint(8) unsigned NOT NULL default '0',
  filename varchar(200) NOT NULL default '',
  place varchar(100) NOT NULL default '',
  glider varchar(50) NOT NULL default '',
  gliderBrandID smallint(5) unsigned NOT NULL default '0',
  comments text NOT NULL,
  linkURL varchar(200) NOT NULL default '',
  hasPhotos tinyint(3) unsigned NOT NULL default '0',
  photo1Filename varchar(150) NOT NULL default '',
  photo2Filename varchar(150) NOT NULL default '',
  photo3Filename varchar(150) NOT NULL default '',
  photo4Filename varchar(150) NOT NULL default '',
  photo5Filename varchar(150) NOT NULL default '',
  photo6Filename varchar(150) NOT NULL default '',
  takeoffID mediumint(9) NOT NULL default '0',
  takeoffVinicity float NOT NULL default '0',
  landingID mediumint(9) NOT NULL default '0',
  landingVinicity float NOT NULL default '0',
  `DATE` date NOT NULL default '0000-00-00',
  timezone float NOT NULL default '0',
  MAX_SPEED float NOT NULL default '0',
  MEAN_SPEED float NOT NULL default '0',
  MAX_ALT int(11) NOT NULL default '0',
  MIN_ALT int(11) NOT NULL default '0',
  TAKEOFF_ALT int(11) NOT NULL default '0',
  MAX_VARIO float NOT NULL default '0',
  MIN_VARIO float NOT NULL default '0',
  LINEAR_DISTANCE bigint(20) NOT NULL default '0',
  MAX_LINEAR_DISTANCE bigint(20) NOT NULL default '0',
  START_TIME mediumint(9) NOT NULL default '0',
  END_TIME mediumint(9) NOT NULL default '0',
  DURATION mediumint(9) NOT NULL default '0',
  BEST_FLIGHT_TYPE varchar(30) NOT NULL default '',
  FLIGHT_KM float NOT NULL default '0',
  FLIGHT_POINTS float NOT NULL default '0',
  autoScore float NOT NULL default '0',
  isLive tinyint(3) unsigned NOT NULL default '0',
  externalFlightType tinyint(3) unsigned NOT NULL default '0',
  forceBounds tinyint(3) unsigned NOT NULL default '0',
  firstPointTM int(10) unsigned NOT NULL default '0',
  firstLat float NOT NULL,
  firstLon float NOT NULL,
  lastPointTM int(10) unsigned NOT NULL default '0',
  lastLat float NOT NULL,
  lastLon float NOT NULL,
  FIRST_POINT varchar(50) NOT NULL default '',
  LAST_POINT varchar(50) NOT NULL default '',
  turnpoint1 varchar(100) NOT NULL default '',
  turnpoint2 varchar(100) NOT NULL default '',
  turnpoint3 varchar(100) NOT NULL default '',
  turnpoint4 varchar(100) NOT NULL default '',
  turnpoint5 varchar(100) NOT NULL default '',
  olcRefNum varchar(30) NOT NULL default '',
  olcFilename varchar(12) NOT NULL default '',
  olcDateSubmited datetime NOT NULL default '0000-00-00 00:00:00',
  private tinyint(3) unsigned NOT NULL default '0',
  gpsTrack tinyint(3) unsigned NOT NULL default '1',
  grecord smallint(6) NOT NULL default '0',
  validated smallint(6) NOT NULL default '0',
  validationMessage text NOT NULL,
  airspaceCheck tinyint(4) NOT NULL default '0',
  airspaceCheckFinal tinyint(4) NOT NULL default '0',
  airspaceCheckMsg text NOT NULL,
  checkedBy varchar(100) NOT NULL default '',
  NACid int(10) unsigned NOT NULL default '0',
  NACclubID bigint(20) NOT NULL default '0',
  `hash` varchar(100) NOT NULL default '',
  batchOpProcessed tinyint(3) unsigned NOT NULL default '0',
  PRIMARY KEY  (ID),
  KEY userID (userID),
  KEY takeoffID (takeoffID),
  KEY takeoffID_2 (takeoffID),
  KEY NACClubIndex (NACclubID,NACid)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ;

INSERT INTO `leonardo_flights_new`
SELECT *
FROM `leonardo_flights` ;


ALTER TABLE `leonardo_flights` RENAME `leonardo_flights_iso` ;

ALTER TABLE `leonardo_flights_new` RENAME `leonardo_flights` ;



