CREATE TABLE leonardo_pilots_new (
`pilotID` bigint( 20 ) NOT NULL default '0',
`serverID` smallint( 5 ) unsigned NOT NULL default '0',
`countryCode` char( 2 ) NOT NULL default '',
`CIVL_ID` mediumint( 8 ) unsigned NOT NULL default '0',
`NACid` int( 10 ) unsigned NOT NULL default '0',
`NACmemberID` bigint( 20 ) unsigned NOT NULL default '0',
`NACclubID` bigint( 20 ) NOT NULL default '0',
`olcBirthDate` varchar( 8 ) NOT NULL default '',
`olcFirstName` varchar( 100 ) NOT NULL default '',
`olcLastName` varchar( 100 ) NOT NULL default '',
`olcCallSign` varchar( 50 ) NOT NULL default '',
`olcFilenameSuffix` varchar( 4 ) NOT NULL default '',
`olcAutoSubmit` tinyint( 4 ) NOT NULL default '0',
`FirstName` varchar( 40 ) NOT NULL default '',
`LastName` varchar( 50 ) NOT NULL default '',
`clubID` mediumint( 8 ) unsigned NOT NULL default '0',
`sponsor` varchar( 255 ) default NULL ,
`Sex` varchar( 6 ) NOT NULL default '',
`Birthdate` varchar( 15 ) NOT NULL default '',
`BirthdateHideMask` varchar( 10 ) NOT NULL default 'xx.xx.xxxx',
`Occupation` varchar( 100 ) NOT NULL default '',
`MartialStatus` varchar( 20 ) NOT NULL default '',
`OtherInterests` longtext NOT NULL ,
`PersonalWebPage` varchar( 150 ) NOT NULL default '',
`PilotLicence` varchar( 100 ) NOT NULL default '',
`BestMemory` longtext NOT NULL ,
`WorstMemory` longtext NOT NULL ,
`Training` varchar( 200 ) NOT NULL default '',
`personalDistance` varchar( 150 ) NOT NULL default '',
`personalHeight` varchar( 150 ) NOT NULL default '',
`glider` varchar( 200 ) NOT NULL default '',
`FlyingSince` varchar( 100 ) NOT NULL default '',
`HoursFlown` varchar( 50 ) NOT NULL default '',
`HoursPerYear` varchar( 50 ) NOT NULL default '',
`FavoriteLocation` varchar( 250 ) NOT NULL default '',
`UsualLocation` varchar( 150 ) NOT NULL default '',
`FavoriteBooks` varchar( 150 ) NOT NULL default '',
`FavoriteActors` varchar( 150 ) NOT NULL default '',
`FavoriteSingers` varchar( 150 ) NOT NULL default '',
`FavoriteMovies` varchar( 150 ) NOT NULL default '',
`FavoriteSite` varchar( 150 ) NOT NULL default '',
`Sign` varchar( 40 ) NOT NULL default '',
`Spiral` varchar( 60 ) NOT NULL default '',
`Bline` varchar( 100 ) NOT NULL default '',
`FullStall` varchar( 100 ) NOT NULL default '',
`Sat` varchar( 100 ) NOT NULL default '',
`AsymmetricSpiral` varchar( 100 ) NOT NULL default '',
`Spin` varchar( 100 ) NOT NULL default '',
`OtherAcro` varchar( 150 ) NOT NULL default '',
`camera` varchar( 150 ) NOT NULL default '',
`camcorder` varchar( 150 ) NOT NULL default '',
`Vario` varchar( 60 ) NOT NULL default '',
`GPS` varchar( 60 ) NOT NULL default '',
`Harness` varchar( 60 ) NOT NULL default '',
`Reserve` varchar( 60 ) NOT NULL default '',
`Helmet` varchar( 60 ) NOT NULL default '',
`PilotPhoto` varchar( 30 ) NOT NULL default '',
`FirstOlcYear` int( 10 ) NOT NULL default '0',
PRIMARY KEY ( `pilotID` , `serverID` )
) ENGINE = MYISAM DEFAULT CHARSET = utf8 ;

INSERT INTO `leonardo_pilots_new` SELECT * FROM `leonardo_pilots` ;


ALTER TABLE `leonardo_pilots` RENAME `leonardo_pilots_iso` ;

ALTER TABLE `leonardo_pilots_new` RENAME `leonardo_pilots` ;
